topics: [localtest, localtest2]
partitions: [0-9, 0-9]
bootstrap.servers: 127.0.0.1:9092,127.0.0.1:9092
key.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
group.id: index
heartbeat.interval.ms: 20000
max.partition.fetch.bytes: 5242880
request.timeout.ms: 60000
session.timeout.ms: 30000
group.max.session.timeout.ms: 60000
auto.offset.reset: earliest
enable.auto.commit: false
