kafka:
  topics: ["localtest"]
  partitions: ["0-9"]
  autoConsume: false
  cunsumerNum: 2
  bootstrap.servers: 127.0.0.1:9091,127.0.0.1:9092
  key.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  group.id: index
  heartbeat.interval.ms: 20000
  max.partition.fetch.bytes: 5242880
  request.timeout.ms: 60000
  session.timeout.ms: 30000
  group.max.session.timeout.ms: 60000
  auto.offset.reset: earliest
  enable.auto.commit: false

index:
  cluster: es5-test
  url: 127.0.0.1:9301,127.0.0.1:9303
  namespace: nouuid
  type: test
  idFields: localAppId,type
  bulkSize: 10

server:




